static/styles/styles.less

Nowrap on sidebar left links

---

static/styles/styles.less

Updated font weights on left nav

---

static/styles/styles.less

Align nav to content as per request

---

src/angular/10b-declarative-state/declarative-state.md
src/angular/10b-declarative-state/declarative.sample.html
src/angular/10b-declarative-state/flatMap.html
src/angular/10b-declarative-state/imperative.sample.html
src/angular/10b-declarative-state/map.html
src/angular/10b-declarative-state/restaurant.component.html
src/angular/10b-declarative-state/restaurant.component.spec.ts
src/angular/10b-declarative-state/restaurant.component.ts
src/angular/10b-declarative-state/shareReplay.html
src/angular/10b-declarative-state/startWith.html
src/angular/10b-declarative-state/tap.html

I've gone over this initial draft with Jennifer. She thought the exercise solution code was well implemented but had the following suggestions for the copy which I'll correct in forthcoming commits:
[ ] - Don't assume that readers will have done the RxJS training
[ ] - Give an explanation of each operator the solution uses along with Codepen examples
[ ] - Give an explanation of the concept of state
[ ] - Remove highlighting of blank lines in solution
Along with fixing the final test:
[ ] - Finish updating last failing test (requires modified service method)

angular declarative state exercise

---

.gitignore
package.json
scripts/hubspot-publish/hubspot-publisher.js
scripts/hubspot-publish/user-prompts.js
templates/layout.mustache

for #103, #85, #101 
- Adds the page description as the meta tag description for each page
- Updates the publish script to ask users to confirm before deleting a page on bitovi.com/academy
- I looked into the HubSpot adblock integration issue and determined it was not a problem (the problem had to do with my local setup and not adblock)

Added description to each page, updated publish script

---

src/angular/11-declarative-state/declarative-state.md
src/angular/11-declarative-state/ideal.component.html
src/angular/11-declarative-state/ideal.component.ts

Added this a separate PR so it can have it's own discussion and review.

adding advanced solution to end of declarative state module

---

src/angular/11-declarative-state/ideal.component.html
src/angular/11-declarative-state/ideal.component.ts

resolving TODOs
break up several long lines

resolve ideal declarative state todos

---

package.json
src/web-components/custom-events.md
src/web-components/customize-header.md
src/web-components/display-markers.md
src/web-components/listing-routes.md
src/web-components/map-view.md
src/web-components/our-first-component.md
src/web-components/selecting-route.md
src/web-components/slotted-content.md
src/web-components/templates.md
src/web-components/web-components.md
src/web-components/why-web-components.md

This is an introductory course on web components. It goes over all of
the core APIs while building a bus tracker component (based on the CanJS
guide).

Learn web components training

---

src/technology-consulting/11-ending-a-project.md
src/technology-consulting/4-development.md
src/technology-consulting/5-communication.md
src/technology-consulting/8-sales-to-delivery.md
src/technology-consulting/9-ending-a-project.md
src/technology-consulting/technology-consulting.md

Completes documentation work of https://github.com/bitovi/bitovi/issues/386.

Tech consulting transition overhaul

---

src/technology-consulting/5-communication.md

Soft Skills - Communication

---

src/javascript/7-classes.md
src/javascript/8-promises.md
src/rxjs/10-show-paying.md

Just went through the promises lesson, I fixed any small typos, double checked all links are working and tested all the code in codepen. Everything looks good. 
@justinbmeyer I'm happy to merge this and deploy the changes if you're good to go on it
Just want to double check that we're still deploying academy using the `npm run publish` command?

Promises final revision

---

package.json
src/bit-u.md

Fix calendar events card vertical layout

---

src/react/1-setting-up-your-environment.md
src/react/2-intro-to-jsx.md
src/react/3-components.md

Add fixes for typos and clarification on event example/how to click onto Codepen.

React intro fixes

---

src/react/6-stateful-hooks.md
src/react/7-controlled-vs-uncontrolled.md
src/react/9-managing-complex-state.md

Fixes typos and code example in stateful hooks.

React state edits

---

src/typescript/4-functions.md
src/typescript/5-classes.md
src/typescript/6-interfaces.md

fix typo and dnaCost better description

---

src/typescript/8-utility-types.md

Typescript utility types

---

src/typescript/3-configuration.md
src/typescript/modules.md

typescript: eslint content

---

src/angular/3-creating-components/angular.json
src/angular/3-creating-components/creating-components.md
src/angular/3-creating-components/home.component.spec.ts
src/angular/3-creating-components/home.component.ts
src/angular/3-creating-components/restaurant.component.html
src/angular/3-creating-components/restaurant.component.spec.ts
src/angular/3-creating-components/restaurant.component.ts
static/styles/styles.less

- update angular.json to angular 13
- add DOM link
- fix broken angular link for "property-binding"
- fix broken "Exercise Description" link
- add restart server command "Ctrl + C"
- highlight temporary css fix
- update tests to angular 13
- update several files and line highlights

Page Updates: creating-components

---

src/angular/3a-pipes/3a-pipes.md
src/angular/3a-pipes/image-url.pipe.spec.ts
src/angular/3a-pipes/image-url.pipe.ts
src/angular/3a-pipes/restaurant.component.html
src/angular/3a-pipes/restaurant.component.spec-with-pipe.ts

- replace "value we can to change" text with "value we want to change"
- update test to angular 13, fix let to const
- add line highlights

Page Updates: creating-pipes

---

src/angular/4-adding-routing/adding-routing.md
src/angular/4-adding-routing/app-routing.module.ts
src/angular/4-adding-routing/app.component.spec.ts

- fix several text mistakes
- update test and files to Angular 13

Page Updates: adding-routing

---

src/angular/5-creating-navigation/app.component.html
src/angular/5-creating-navigation/app.component.spec.ts
src/angular/5-creating-navigation/creating-navigation.md

- update tests to angular 13
- prettier formatting

Page Updates: creating-navigation

---

src/angular/6-restaurant-service/app.module.ts
src/angular/6-restaurant-service/restaurant-service.md
src/angular/6-restaurant-service/restaurant-starter.ts
src/angular/6-restaurant-service/restaurant.service-1.ts
src/angular/6-restaurant-service/restaurant.service-with-interface.spec.ts
src/angular/6-restaurant-service/restaurant.service.spec.ts
src/angular/6-restaurant-service/restaurant.service.ts
src/angular/6-restaurant-service/restaurant.ts

- several text fixes
- update tests and files to Angular 13
- update line highlights

Page Updates: restaurant-service

---

src/angular/7-pull-restaurant-data-into-view/app.component.spec.ts
src/angular/7-pull-restaurant-data-into-view/pull-restaurant-data-into-view.md
src/angular/7-pull-restaurant-data-into-view/restaurant.component-service.ts
src/angular/7-pull-restaurant-data-into-view/restaurant.component.html
src/angular/7-pull-restaurant-data-into-view/restaurant.component.spec-service.ts
src/angular/7-pull-restaurant-data-into-view/restaurant.component.spec.ts
src/angular/7-pull-restaurant-data-into-view/restaurant.component.ts

- update tests and files to Angular 13
- minor text fixes

Page Updates: pull-restaurant-data-into-view

---

src/angular/8-state-city-options/app.component.spec.ts
src/angular/8-state-city-options/app.module.ts
src/angular/8-state-city-options/restaurant.component-starter.html
src/angular/8-state-city-options/restaurant.component-starter.ts
src/angular/8-state-city-options/restaurant.component.html
src/angular/8-state-city-options/restaurant.component.spec.ts
src/angular/8-state-city-options/restaurant.component.ts
src/angular/8-state-city-options/state-city-options.md

- replace "dom" with "DOM" (uppercase)
- minor text fixes
- update tests and files to Angular 13, update line-highlights

Page Updates: state-city-options

---

src/angular/12-writing-unit-tests/restaurant.service.spec-withrestaurant.ts
src/angular/12-writing-unit-tests/restaurant.service.ts
src/angular/12-writing-unit-tests/writing-unit-tests.md

Page Updates: writing-unit-tests

---

src/angular/13-nested-routes/app-routing.module.ts
src/angular/13-nested-routes/app.component.spec.ts
src/angular/13-nested-routes/detail.component-starter.ts
src/angular/13-nested-routes/detail.component.html
src/angular/13-nested-routes/detail.component.spec.ts
src/angular/13-nested-routes/detail.component.ts
src/angular/13-nested-routes/nested-routes.md

Page Updates: nested-routes

---

package.json
static/styles/styles.less
templates/content.mustache

prev-next component @ https://github.com/bitovi/bit-docs-html-prev-next

previous and next links

---

src/angular/15-directive/15-directive.md
src/angular/15-directive/directive.html
src/angular/15-directive/only-numbers.directive.spec.ts
src/angular/15-directive/only-numbers.directive.ts
src/angular/15-directive/order.component.directive.html

- typo fixes
- fix broken link
- update code formatting

Page Updates: creating-directive

---

src/angular/16-order-service/2-order.service.spec.ts
src/angular/16-order-service/order-2.service.ts
src/angular/16-order-service/order-service.md
src/angular/16-order-service/order.component-solution.ts
src/angular/16-order-service/order.component.html
src/angular/16-order-service/order.component.spec.ts
src/angular/16-order-service/order.component.ts
src/angular/16-order-service/order.service-interfaces.ts

Page Updates: order-service

---

src/angular/18-item-total-pipe/app.component.spec.ts
src/angular/18-item-total-pipe/app.module-currency-pipe.ts
src/angular/18-item-total-pipe/app.module.ts
src/angular/18-item-total-pipe/history.component.spec.ts
src/angular/18-item-total-pipe/item-total-pipe.md
src/angular/18-item-total-pipe/item-total.pipe.spec.ts
src/angular/18-item-total-pipe/item-total.pipe.ts
src/angular/18-item-total-pipe/list.component-currency.html
src/angular/18-item-total-pipe/list.component.html
src/angular/18-item-total-pipe/list.component.spec.ts
src/angular/18-item-total-pipe/menu-items-1.component-currency.html
src/angular/18-item-total-pipe/order.component-solution.ts
src/angular/18-item-total-pipe/order.component.html
src/angular/18-item-total-pipe/order.component.spec.ts
src/angular/18-item-total-pipe/understanding-how-pipes-are-provided.html

Page Updates: item-total-pipe

---

src/rxjs/0-basics.md
src/rxjs/1-angular-solution.html
src/rxjs/1-angular-start.html
src/rxjs/1-angular.md
src/rxjs/10-show-paying.html
src/rxjs/10-show-paying.md
src/rxjs/11-disable-while-pending.html
src/rxjs/11-disable-while-pending.md
src/rxjs/2-clean-card-number.html
src/rxjs/2-clean-card-number.md
src/rxjs/3-card-error.html
src/rxjs/4-debugging.html
src/rxjs/4-debugging.md
src/rxjs/5-error-on-blur.html
src/rxjs/5-error-on-blur.md
src/rxjs/6-expiry.html
src/rxjs/7-cvc.html
src/rxjs/8-disable-pay-button.html
src/rxjs/8-disable-pay-button.md
src/rxjs/9-request-payment.html
src/rxjs/9-request-payment.md
src/rxjs/rxjs.md

Update RxJS training content and code to utilize RxJS 7.4 and the latest version of Angular 12 (the last version readily available on codepen)

Update RxJS Training to Angular 12 + RxJS 7

---

src/angular/12-writing-unit-tests/writing-unit-tests.md

Addresses issues described in https://bitovi.atlassian.net/browse/NGACAD-53?atlOrigin=eyJpIjoiZWQyNGU3NzI4NDMwNDdjZWE3YmFhZGRjZDNhM2U3ZjMiLCJwIjoiaiJ9

Angular: Update "Writing Unit Tests" page

---

src/rxjs/0-basics.md
src/rxjs/1-angular-solution.html
src/rxjs/1-angular-start.html
src/rxjs/1-angular.md
src/rxjs/10-show-paying.html
src/rxjs/10-show-paying.md
src/rxjs/11-disable-while-pending.html
src/rxjs/11-disable-while-pending.md
src/rxjs/2-clean-card-number.html
src/rxjs/2-clean-card-number.md
src/rxjs/3-card-error.html
src/rxjs/3-card-error.md
src/rxjs/4-debugging.html
src/rxjs/4-debugging.md
src/rxjs/5-error-on-blur.html
src/rxjs/5-error-on-blur.md
src/rxjs/6-expiry.html
src/rxjs/6-expiry.md
src/rxjs/7-cvc.html
src/rxjs/7-cvc.md
src/rxjs/8-disable-pay-button.html
src/rxjs/8-disable-pay-button.md
src/rxjs/9-request-payment.html
src/rxjs/9-request-payment.md

- replace var with let/const
- prefer arrow functions
- NGACAD-46: replace deprecated Observable.create with new Observable
- styling closer to prettier
- NGACAD-45: replace publish-subscribe pattern with observer pattern references

RxJS Updates

---

src/angular/6-restaurant-service/restaurant-service.md

Fixes issue described in ticket [NGACAD-41](https://bitovi.atlassian.net/browse/NGACAD-41):
images object should not be an array in interface representation within restaurant-service page

Angular: fix restaurant interface in restaurant-service P2 details

---

src/angular/18-item-total-pipe/item-total-pipe.md
src/angular/18-item-total-pipe/order.component.html

Addresses [NGACAD-56](https://bitovi.atlassian.net/browse/NGACAD-56?atlOrigin=eyJpIjoiODhlNWUyOWE0YThlNGZkOWE1ZTZiZWFjNzU5NDY0OWQiLCJwIjoiaiJ9)
- Add explanation of how pipe should be used:
- Add pipe to list template
- Call pipe transform method in order component
- Remove extra $ from templates where currency pipe is in use

Angular(item-total-pipe): Fix and expand section

---

src/typescript/1-why-typescript.md

Addresses [NGACAD-62](https://bitovi.atlassian.net/browse/NGACAD-62)

TypeScript: correct first exercise filename

---

src/typescript/4-types.md

Addresses [NGACAD-63](https://bitovi.atlassian.net/browse/NGACAD-63)
- Adds details about `unknown` type
- Expands details about `any` type

TypeScript: add unknown type info and expand any type info

---

src/angular/18-item-total-pipe/item-total-pipe.md

- separate into sections like other lessons
- capitalize Pipe
- remove unnecessary link
- improve text

Angular: improve item total pipe lesson

---

src/react/10-context-hooks.md
src/react/2-intro-to-jsx.md
src/react/3-components.md
src/react/4-props.md
src/react/5-styling-in-react.md
src/react/6-stateful-hooks.md
src/react/7-controlled-vs-uncontrolled.md
src/react/8-optimizaton-hooks.md
src/react/9-managing-complex-state.md

touch ups from - https://bitovi.atlassian.net/browse/ACADEMY-15

Academy 15 - React Touch Ups

---

src/typescript/1-why-typescript.md
src/typescript/10-utility-types.md
src/typescript/2-ide-support.md
src/typescript/3-configuration.md
src/typescript/4-types.md
src/typescript/5-functions.md
src/typescript/6-classes.md
src/typescript/7-interfaces.md
src/typescript/8-keyof-typeof.md
src/typescript/9-generics.md
src/typescript/typescript.md

addresses: https://bitovi.atlassian.net/browse/ACADEMY-18

Academy 18 ready type script

---

src/advanced-typescript/01-typing-systems/typing-systems.md
src/advanced-typescript/02-generics-with-constraints/generics-with-constraints.md
src/advanced-typescript/03-index-accessed-types/index-accessed-types.md
src/advanced-typescript/04-mapped-types/mapped-types.md
src/advanced-typescript/05-conditional-types/conditional-types.md
src/advanced-typescript/06-template-literal-types/template-literal-types.md
src/advanced-typescript/advanced-typescript.md

Generics With Constraints - a link is broken on prod, but not local. The fix may or may not be effective.
Mapped Types - image is broken on prod, but not local. Fix may or may not be effective.
Changed links to CodeSandbox to link to exercise file. Added highlighting to solutions. Adding wording updates for clarity. Updated slack link and "next steps" on main page.

Academy 26 - Advanced Typescript Audit Complete

---

static/static.js
templates/layout.mustache

resolves https://bitovi.atlassian.net/browse/ACADEMY-36

academy-36: refine popup

---

src/canjs/1-setup/setup.md
src/canjs/10-connection-list/connection-list.md
src/canjs/11-toggle-save/toggle-save.md
src/canjs/12-connection-destroy/connection-destroy.md
src/canjs/13-component-create/component-create.md
src/canjs/14-component-edit/component-edit.md
src/canjs/15-setter-toggle/setter-toggle.md
src/canjs/16-clear-all-completed/clear-all-completed.md
src/canjs/17-routing/routing.md
src/canjs/2-define-todo/define-todo.md
src/canjs/3-define-todo-list/define-todo-list.md
src/canjs/4-render-todos/render-todos.md
src/canjs/5-toggle-event/toggle-event.md
src/canjs/6-toggle-data/toggle-data.md
src/canjs/7-algebra/algebra.md
src/canjs/8-fixtures/fixtures.md
src/canjs/9-connection/connection.md

Addressed issues in ticket: https://bitovi.atlassian.net/browse/ACADEMY-32

ACADEMY - 32 CanJS

---

src/web-components/1-our-first-component/our-first-component.md
src/web-components/10-custom-events/custom-events.md
src/web-components/2-templates/templates.md
src/web-components/3-map-view/map-view.md
src/web-components/4-bus-tracker-component/bus-tracker.md
src/web-components/5-listing-routes/listing-routes.md
src/web-components/6-selecting-route/selecting-route.md
src/web-components/7-display-markers/display-markers.md
src/web-components/8-customize-header/customize-header.md
src/web-components/9-slotted-content/slotted-content.md
src/web-components/web-components.md
src/web-components/why-web-components.md

Addresses all issues in [Academy-22-Ready-Web-Components](https://bitovi.atlassian.net/browse/ACADEMY-22?atlOrigin=eyJpIjoiY2I2OGViYWY2YTQwNGNmODljNzEwYWQzNGY4ZGQwOTciLCJwIjoiaiJ9):
- Removes duplicate "next lesson" links
- Adds lesson link & description in Outine
- Updates links
- Cleans up code blocks

Academy 22 ready web components

---

src/technology-consulting/1-effort.md
src/technology-consulting/2-specific-goals.md
src/technology-consulting/3-prioritization.md
src/technology-consulting/4-development.md
src/technology-consulting/5-communication.md
src/technology-consulting/6-building-rapport.md
src/technology-consulting/7-setting-expectations.md
src/technology-consulting/8-sales-to-delivery.md
src/technology-consulting/9-ending-a-project.md
src/technology-consulting/technology-consulting.md

Basic UI changes only, no content creation.

Academy-24: Technology Consulting

---

src/ngrx/ngrx.md

[AOS2-57](https://bitovi.atlassian.net/browse/AOS2-57?atlOrigin=eyJpIjoiNzE5OGE0MDgyYWE5NGIzMTlkYjYyOTA4N2ViY2Y1Y2IiLCJwIjoiaiJ9)

feature(ngrx): create NgRx lesson outline 

---

src/ngrx/1-why-ngrx/why-ngrx.md
src/ngrx/10-test-redirect-effects/test-redirect-effects.md
src/ngrx/11-create-reducer/create-reducer.md
src/ngrx/12-test-reducer/test-reducer.md
src/ngrx/13-create-selectors/create-selectors.md
src/ngrx/14-test-selectors/test-selectors.md
src/ngrx/15-use-selectors/use-selectors.md
src/ngrx/16-test-used-selectors/test-used-selectors.md
src/ngrx/2-getting-started/getting-started.md
src/ngrx/3-ngrx-init/ngrx-init.md
src/ngrx/4-create-actions/create-actions.md
src/ngrx/5-dispatch-actions/dispatch-actions.md
src/ngrx/6-test-actions/test-actions.md
src/ngrx/7-create-api-effects/create-api-effects.md
src/ngrx/8-test-api-effects/test-api-effects.md
src/ngrx/9-create-redirect-effects/create-redirect-effects.md
src/ngrx/ngrx.md

Jira ticket: [AOS2-58](https://bitovi.atlassian.net/browse/AOS2-58?atlOrigin=eyJpIjoiMWQ3ODU2ZWU4Y2IwNDg4Y2FkZDM1Y2JhMWJhZTA4OTUiLCJwIjoiaiJ9)

feature(ngrx): add stub pages for course steps

---

src/ngrx/10-test-redirect-effects/login.effects.spec.ts
src/ngrx/10-test-redirect-effects/test-redirect-effects.md
src/ngrx/12-test-reducer/login.reducer.spec.ts
src/ngrx/12-test-reducer/login.selectors.spec.ts
src/ngrx/12-test-reducer/test-reducer.md
src/ngrx/14-test-selectors/login.selectors.spec.ts
src/ngrx/14-test-selectors/test-selectors.md
src/ngrx/16-test-used-selectors/dashboard.component.spec.ts
src/ngrx/16-test-used-selectors/test-used-selectors.md
src/ngrx/6-test-actions/dashboard.component.spec.ts
src/ngrx/6-test-actions/login.component.spec.ts
src/ngrx/6-test-actions/test-actions.md
src/ngrx/8-test-api-effects/login.effects.spec.ts
src/ngrx/8-test-api-effects/test-api-effects.md

[Jira AOS2-62](https://bitovi.atlassian.net/browse/AOS2-62?atlOrigin=eyJpIjoiNTE0MDY4NGVhYWU5NDgzYjllZjc2NTIxMDZiYjAyZDgiLCJwIjoiaiJ9)
Following [notes from Mark](https://bitovi.atlassian.net/wiki/spaces/NG/pages/221446274/Notes+on+each+section+branch)

feature(ngrx): add content to test parts

---

src/ngrx/1-why-ngrx/why-ngrx.md
src/ngrx/10-test-redirect-effects/test-redirect-effects.md
src/ngrx/11-create-reducer/create-reducer.md
src/ngrx/12-test-reducer/test-reducer.md
src/ngrx/13-create-selectors/create-selectors.md
src/ngrx/14-test-selectors/test-selectors.md
src/ngrx/15-use-selectors/contact.component.ts
src/ngrx/15-use-selectors/use-selectors.md
src/ngrx/16-test-used-selectors/test-used-selectors.md
src/ngrx/2-getting-started/getting-started.md
src/ngrx/3-ngrx-init/ngrx-init.md
src/ngrx/4-create-actions/create-actions.md
src/ngrx/5-dispatch-actions/dispatch-actions.md
src/ngrx/6-test-actions/test-actions.md
src/ngrx/7-create-api-effects/create-api-effects.md
src/ngrx/8-test-api-effects/test-api-effects.md
src/ngrx/9-create-redirect-effects/create-redirect-effects.md
src/ngrx/ngrx.md

1. Cleaned up uppercases
2. Removed unnecessary use of "Feature"
3. Added extra newlines at the end of each body of text that has a header within the markdown (unless it's followed up by a sub-header)
4. Added content for `Creating Selectors` section
5. Added content for `Using Selectors` section
6. Revised `Why Use NgRx` section

feat(ngrx): added content for creating and using selectors, revised why use ngrx section

---

src/ngrx/10-test-redirect-effects/test-redirect-effects.md
src/ngrx/11-create-reducer/create-reducer.md
src/ngrx/12-test-reducer/test-reducer.md
src/ngrx/13-create-selectors/create-selectors.md
src/ngrx/14-test-selectors/test-selectors.md
src/ngrx/15-use-selectors/use-selectors.md
src/ngrx/16-test-used-selectors/test-used-selectors.md
src/ngrx/3-ngrx-init/app.module.before-formatting.ts
src/ngrx/3-ngrx-init/ngrx-init.md
src/ngrx/4-create-actions/create-actions.md
src/ngrx/5-dispatch-actions/dispatch-actions.md
src/ngrx/6-test-actions/test-actions.md
src/ngrx/7-create-api-effects/create-api-effects.md
src/ngrx/8-test-api-effects/test-api-effects.md
src/ngrx/9-create-redirect-effects/create-redirect-effects.md

https://bitovi.atlassian.net/browse/AOS2-73
Resolving the following issues reported: https://github.com/bitovi/academy/issues?q=is%3Aopen+is%3Aissue+project%3Abitovi%2Facademy%2F1+author%3Aramblinjan
1. Fixed "Disptch" typo https://github.com/bitovi/academy/issues/353
2. Added more context on what's changing on `create-actions` section to make it more clear that we're updating the imports https://github.com/bitovi/academy/issues/352
3. Added alternative suggestion to checking code diffs at the end of each section. ex: `git diff origin/ngrx-init` https://github.com/bitovi/academy/issues/351
4. Used manual highlighting to show adding `LoginPartialState`. This resolves an issue where auto diff highlighting is incorrect https://github.com/bitovi/academy/issues/350
5. Added instructions on how …

fix(ngrx) resolving review notes

---

src/ngrx/10-test-redirect-effects/test-redirect-effects.md
src/ngrx/11-create-reducer/create-reducer.md
src/ngrx/12-test-reducer/test-reducer.md
src/ngrx/13-create-selectors/create-selectors.md
src/ngrx/14-test-selectors/test-selectors.md
src/ngrx/15-use-selectors/use-selectors.md
src/ngrx/16-test-used-selectors/test-used-selectors.md
src/ngrx/2-getting-started/getting-started.md
src/ngrx/3-ngrx-init/ngrx-init.md
src/ngrx/4-create-actions/create-actions.md
src/ngrx/5-dispatch-actions/dispatch-actions.md
src/ngrx/6-test-actions/test-actions.md
src/ngrx/7-create-api-effects/create-api-effects.md
src/ngrx/8-test-api-effects/test-api-effects.md
src/ngrx/9-create-redirect-effects/create-redirect-effects.md

[Jira AOS2-77](https://bitovi.atlassian.net/browse/AOS2-77?atlOrigin=eyJpIjoiYjBkODNmNTllMTA2NDY4NGJkNDQyMzE4MGIwN2ZmY2MiLCJwIjoiaiJ9)
- Refer to pages as "sections" instead of "parts"
[AOS2-77]: https://bitovi.atlassian.net/browse/AOS2-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AOS2-77]: https://bitovi.atlassian.net/browse/AOS2-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ngrx): replace word part with section

---

src/ngrx/11-create-reducer/contact.ts
src/ngrx/11-create-reducer/counter.reducer-with-reset-handler.ts
src/ngrx/11-create-reducer/counter.reducer-with-set-zero.ts
src/ngrx/11-create-reducer/counter.reducer.ts
src/ngrx/11-create-reducer/create-reducer.md
src/ngrx/15-use-selectors/contact.component.ts
src/ngrx/4-create-actions/create-actions.md
src/ngrx/5-dispatch-actions/contact.component.ts
src/ngrx/5-dispatch-actions/dispatch-actions.md
src/ngrx/7-create-api-effects/contact.effects-handle-success.ts
src/ngrx/7-create-api-effects/contact.effects-initial-setup.ts
src/ngrx/7-create-api-effects/contact.effects.ts
src/ngrx/7-create-api-effects/create-api-effects.md
src/ngrx/9-create-redirect-effects/contact.effects.ts
src/ngrx/9-create-redirect-effects/create-redirect-effects.md

[Jira AOS2-76](https://bitovi.atlassian.net/browse/AOS2-76?atlOrigin=eyJpIjoiZjE0ZWMwNmZmMGZhNDUyMzhhNWVlOWI3ZGVjNGIwMzgiLCJwIjoiaiJ9)
[AOS2-76]: https://bitovi.atlassian.net/browse/AOS2-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AOS2-76]: https://bitovi.atlassian.net/browse/AOS2-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ngrx): add disclaimer about code blocks not part of repo

---

src/ngrx/7-create-api-effects/create-api-effects.md
src/ngrx/7-create-api-effects/exhaust-map-example.html

Added flattening operators / `exhaustMap` explanation in Effects section

feat(ngrx): flattening operators / exhaustMap explanation in effects section

---

src/ngrx/10-test-redirect-effects/test-redirect-effects.md
src/ngrx/11-create-reducer/create-reducer.md
src/ngrx/11-create-reducer/login.reducer.spec.ts
src/ngrx/11-create-reducer/login.selectors.spec.ts
src/ngrx/12-test-reducer/test-reducer.md
src/ngrx/13-create-selectors/create-selectors.md
src/ngrx/14-test-selectors/test-selectors.md
src/ngrx/15-use-selectors/use-selectors.md
src/ngrx/16-test-used-selectors/test-used-selectors.md
src/ngrx/4-create-actions/create-actions.md
src/ngrx/5-dispatch-actions/dashboard.component.spec.ts
src/ngrx/5-dispatch-actions/dispatch-actions.md
src/ngrx/5-dispatch-actions/login.component.spec.ts
src/ngrx/6-test-actions/test-actions.md
src/ngrx/7-create-api-effects/create-api-effects.md
src/ngrx/7-create-api-effects/login.effects.spec.ts
src/ngrx/8-test-api-effects/test-api-effects.md
src/ngrx/9-create-redirect-effects/create-redirect-effects.md

Jira: https://bitovi.atlassian.net/browse/AOS2-86
1. All test pages include an outline for the content they will have
2. All test pages now use diffs when showing all the files changed for that section instead of sources
3. Minor refactor to newlines when using `<source>` tags within `ngrx` course
In this PR, each testing section has a description section that will be updated in their own PRs. For now I have moved the text we had at the bottom of the page to it and added a `TODO`.

feat(ngrx): refactored test pages list steps for an outline

---

src/docker/docker.md

This PR changes the links and description in the "Before You Begin" section of "Learn Docker" module. It also changes the video embed link, on top of the page.

MKTG-655:Changed Slack link to Discord and updated video embed

---

src/program-management-with-jira/program-management.md

Your branch is up to date with 'origin/jan24-academy'.
Changes to be committed:
modified:   src/program-management-with-jira/program-management.md
Untracked files:
static/img/program-management-with-jira/home/jan24-workshop.png

 On branch jan24-academy

---

src/program-management-with-jira/program-management.md

Updated date/time of January 24th webinar

Jan24 academy

---

src/angular/17-order-history-component/app.component.html
src/angular/17-order-history-component/order-history-component.md
src/angular/4-adding-routing/app.component.html
src/angular/5-creating-navigation/app.component.problem.html
src/angular/5-creating-navigation/app.component.solution.html
src/angular/5-creating-navigation/creating-navigation.md
src/angular/5-creating-navigation/router-link-active-template.html

Lots of fixes to the text and code, including rearranging the page to follow the “Overview -> Problem -> What you need to know -> Technical requirements -> Setup -> How to verify…” structure and improving the naming & explanation around `userLink`.

Clean up the “Creating Navigation” section

---

src/angular/14-building-order-form/building-order-form.md
src/angular/16-order-service/order-service.md
src/angular/17-order-history-component/order-history-component.md
src/angular/18-item-total-pipe/item-total-pipe.md
src/angular/19-real-time-connections/real-time-connections.md
src/angular/3-creating-components/creating-components.md
src/angular/6-restaurant-service/restaurant-service.md
src/angular/7-pull-restaurant-data-into-view/pull-restaurant-data-into-view.md
src/angular/9-form-value-changes/form-value-changes.md
src/ngrx/11-create-reducer/create-reducer.md
src/ngrx/13-create-selectors/create-selectors.md
src/ngrx/15-use-selectors/use-selectors.md
src/ngrx/4-create-actions/create-actions.md
src/ngrx/5-dispatch-actions/dispatch-actions.md
src/ngrx/7-create-api-effects/create-api-effects.md
src/ngrx/9-create-redirect-effects/create-redirect-effects.md

I renamed this page so it’s more clear what we’re going to learn and not focused on PMO. This also includes lots of little fixes to the text and code.

Clean up the “Rendering Data in Components” section

---

src/angular/1-why-angular/why-angular.md
src/angular/12-writing-unit-tests/writing-unit-tests.md

Minor fixes to the text and code, including a section that reviews the individual pieces of testing code all together.

Clean up the “Writing Unit Tests” section

---

src/angular/13-nested-routes/detail.component.ts
src/angular/13-nested-routes/nested-routes.md

Lots of minor fixes to the text and code, including renaming this page.

Clean up the “Creating Nested Routes” section

---

src/angular/14-building-order-form/building-order-form.md
src/angular/14-building-order-form/component-interaction.html
src/angular/14-building-order-form/output.html
src/angular/2-building-first-app/building-first-app.md
src/typescript/4-types.md

Some minor fixes to the text and code, including renaming this page.

Clean up the “Binding Component Data” section

---

src/angular/15-directive/15-directive.md
src/angular/15-directive/directive.html
src/angular/15-directive/example.ElementRef.ts
src/angular/15-directive/example.HostListener.ts
src/angular/15-directive/example.attribute.ts
src/angular/15-directive/example.component.ts
src/angular/15-directive/example.structural.ts
src/angular/3-creating-components/creating-components.md
src/angular/8-state-city-options/state-city-options.md

Minor fixes to the text and code, including adding examples for most of the directive parts.

Clean up the “Creating Directives” section

---

README.md
package-lock.json
package.json
src/bit-u.md

Make React one of the items on the main menu.

---

src/react-vite/01-intro-to-react/intro-to-react.md

I mostly copied the Angular page: some key considerations  as bullets.
From [Core React Fundamentals](https://bitovi.atlassian.net/wiki/spaces/FRONTEND/pages/570491028/Core+React+Fundamentals)

LD-32 Add Introduction to React.

---

.depcheckrc
README.md
package-lock.json
package.json

Add `concurrent` to spawn two or more processes at the same time (and kill all when one exists).

The start command now rebuilds on source changes.

---

static/styles/styles.less

Add top spacing for inner TOC lists

---

src/react-vite/04-components/components.md

LD-87 Component page content

---

src/react-vite/03-intro-to-jsx/intro-to-jsx.md

Added to the intro to JSX section to introduce some html versus jsx differences before seeing them in the exercise
Fixed the heading hierarchy

Intro to JSX additions

---

src/react-vite/09-making-http-requests/making-http-requests.md
src/react-vite/10-nested-routes/nested-routes.md
src/react-vite/11-controlled-vs-uncontrolled/controlled-vs-uncontrolled.md

Previous structure:
- Managing State
- Handling Side Effects
- Handling User Inputs
- Fetching Data
- Testing
New structure:
- Managing State
- Making HTTP Requests (was Fetching Data)
- Creating Nested Routes (was Handling Side Effects)
- Handling User Inputs
- Testing
Making HTTP Requests was moved up so we can actually fetch state, city, and restaurant data sooner.
Handling Side Effects was removed because the ideas for that section are now covered elsewhere; Creating Nested Routes was added so we have a bridge section for creating the Restaurant Detail and Order pages.

Rearrange the React pages

---

src/react-vite/07-styling-in-react/styling-in-react.md

LD-118 Styling

---

static/styles/styles.less

ToC reduce left-side indent to fit better

---

exercises/react-vite/05-props/01-solution/src/pages/RestaurantList/RestaurantList.tsx
src/react-vite/05-props/props.md

- Add the `key` back to the final solution
- Use a more real name (`SubmitButton`) so the example code looks less contrived
- Add a little section about `children` and `key` to clarify an earlier mention of `undefined` props
- Refine some of the text

Update the “Passing Props” section

---

src/react-vite/09-making-http-requests/making-http-requests.md

This is a very rough draft of some of the content for this page.

Add some content and notes to the “Making HTTP Requests” section

---

static/styles/styles.less

When talking about routing or how to organize files, it would be helpful to have a simple, compact list style so I made this:

A class to display directory or path lists better

---

src/react-vite/09-making-http-requests/dependency-array-empty.tsx
src/react-vite/09-making-http-requests/dependency-array-undefined.tsx
src/react-vite/09-making-http-requests/dependency-array-with-values.tsx
src/react-vite/09-making-http-requests/fetch-with-async.tsx
src/react-vite/09-making-http-requests/fetch-with-promise.tsx
src/react-vite/09-making-http-requests/making-http-requests.md
src/react-vite/09-making-http-requests/useEffect-with-cleanup.tsx

This fleshes out the content with better descriptions and code examples.

Refine the content for “Making HTTP Requests” objective 1

---

exercises/react-vite/10-nested-routes/01-solution/src/main.tsx
exercises/react-vite/10-nested-routes/02-solution/src/main.tsx
src/react-vite/10-nested-routes/nested-routes.md

Does not contain the exercises yet. Might need some tweaking to fit the exercise better.

LD-120 Nested routes

---

package.json

It took me all day to figure out where to put a one line change in bit-docs-prettify. 😭 Anyway - TSX files now look nicer.

You now have TSX syntax highlighting.

---

exercises/react-vite/11-controlled-vs-uncontrolled/01-problem/src/pages/RestaurantOrder/RestaurantOrder.test.tsx
exercises/react-vite/11-controlled-vs-uncontrolled/01-problem/src/pages/RestaurantOrder/RestaurantOrder.tsx
exercises/react-vite/11-controlled-vs-uncontrolled/01-solution/src/pages/RestaurantOrder/RestaurantOrder.test.tsx
exercises/react-vite/11-controlled-vs-uncontrolled/01-solution/src/pages/RestaurantOrder/RestaurantOrder.tsx
exercises/react-vite/11-controlled-vs-uncontrolled/02-problem/src/pages/RestaurantOrder/RestaurantOrder.test.tsx
exercises/react-vite/11-controlled-vs-uncontrolled/02-problem/src/pages/RestaurantOrder/RestaurantOrder.tsx
exercises/react-vite/11-controlled-vs-uncontrolled/02-solution/src/pages/RestaurantOrder/RestaurantOrder.test.tsx
exercises/react-vite/11-controlled-vs-uncontrolled/02-solution/src/pages/RestaurantOrder/RestaurantOrder.tsx
exercises/react-vite/11-controlled-vs-uncontrolled/03-problem/src/pages/RestaurantOrder/RestaurantOrder.test.tsx
exercises/react-vite/11-controlled-vs-uncontrolled/03-problem/src/pages/RestaurantOrder/RestaurantOrder.tsx
exercises/react-vite/11-controlled-vs-uncontrolled/03-solution/src/pages/RestaurantOrder/RestaurantOrder.test.tsx
exercises/react-vite/12-testing/01-problem/src/pages/RestaurantOrder/RestaurantOrder.test.tsx
exercises/react-vite/12-testing/01-problem/src/pages/RestaurantOrder/RestaurantOrder.tsx
exercises/react-vite/12-testing/01-solution/src/pages/RestaurantOrder/RestaurantOrder.test.tsx
exercises/react-vite/12-testing/01-solution/src/pages/RestaurantOrder/RestaurantOrder.tsx

Additionally, this fixes the `Error: Not implemented: window.alert` in the tests.

Update exercise diffs for “Handling User Inputs and Forms”

---

src/react-vite/02-setting-up-your-environment/setting-up-your-environment.md
src/react-vite/03-intro-to-jsx/intro-to-jsx.md

Add config to setup
Add clarity to some text.

Setup and JSX improvements

---

src/react-vite/01-intro-to-react/intro-to-react.md
src/react-vite/react.md

This reorganizes and rewrites the content across the “Learn React” and “Introduction to React” pages.

Refine the “Introduction to React” content

---

src/react-vite/02-setting-up-your-environment/setting-up-your-environment.md

This rearranges the page so it’s broken up into smaller parts that will be easier to have folks do and verify locally.

Fix the heading structure on the “Setting Up Your Environment” page

---

src/react-vite/03-intro-to-jsx/intro-to-jsx.md
src/react-vite/04-components/components.md
src/react-vite/05-props/props.md
src/react-vite/06-routing/routing.md
src/react-vite/07-styling-in-react/styling-in-react.md
src/react-vite/08-stateful-hooks/stateful-hooks.md
src/react-vite/09-making-http-requests/making-http-requests.md
src/react-vite/10-nested-routes/nested-routes.md
src/react-vite/11-controlled-vs-uncontrolled/controlled-vs-uncontrolled.md
src/react-vite/12-testing/testing.md

This updates the pages to follow this structure everywhere:
- Overview
- Objective 1
- Concept A
- Concept B
- Setup 1
- Verify 1
- Exercise 1
- Solution 1
- Next steps

Refine the heading structure on the React pages

---

exercises/react-vite/04-components/01-problem/src/App.tsx
src/react-vite/04-components/components.md
src/react-vite/08-stateful-hooks/stateful-hooks.md

Improvements made while making the slides.

Refine the “Building Components” content

---

src/react-vite/05-props/props.md
src/react-vite/11-controlled-vs-uncontrolled/controlled-vs-uncontrolled.md

Improvements made while making the slides.

Refine the “Passing Props” content

---

src/react-vite/02-setting-up-your-environment/setting-up-your-environment.md
src/react-vite/04-components/components.md
src/react-vite/05-props/props.md

They both seem to be working great without any customization required.

Add more StackBlitz and CodeSandbox links

---

src/react-vite/06-routing/routing.md

Also refine a little bit of the text.

Fix the StackBlitz and CodeSandbox links on “Routing in React”

---

exercises/typescript/06-types/01-problem/package-lock.json
exercises/typescript/06-types/01-problem/package.json
exercises/typescript/06-types/01-problem/src/types/fix-errors.test.ts
exercises/typescript/06-types/01-problem/src/types/fix-errors.ts
exercises/typescript/06-types/01-problem/tsconfig.json
exercises/typescript/06-types/01-solution/package-lock.json
exercises/typescript/06-types/01-solution/package.json
exercises/typescript/06-types/01-solution/src/types/fix-errors.test.ts
exercises/typescript/06-types/01-solution/src/types/fix-errors.ts
exercises/typescript/06-types/01-solution/tsconfig.json
exercises/typescript/06-types/02-problem/package-lock.json
exercises/typescript/06-types/02-problem/package.json
exercises/typescript/06-types/02-problem/src/types/date-exports.test.ts
exercises/typescript/06-types/02-problem/src/types/date-exports.ts
exercises/typescript/06-types/02-problem/tsconfig.json
exercises/typescript/06-types/02-solution/package-lock.json
exercises/typescript/06-types/02-solution/package.json
exercises/typescript/06-types/02-solution/src/types/date-exports.test.ts
exercises/typescript/06-types/02-solution/src/types/date-exports.ts
exercises/typescript/06-types/02-solution/tsconfig.json
src/typescript/06-types/types.md

These are most of the changes for the 'Types' section for the Typescript Academy.
I need a bit of feedback to ensure these changes are right, or if it's worth using a different package for tests.

(LD-278) Update the content & exercises for 'Types'

---

src/typescript/02-ide-support/ide-support.md
src/typescript/02-ide-support/ide-support.txt

- Add a “Next steps” section at the bottom of the page.

Minor edits to the “IDE Support” page

---

src/web-components/8-customize-header/customize-header.md
src/web-components/web-components.md
src/web-components/why-web-components.md

Minor edits to the “Learn Web Components” course

---

src/typescript/typescript.md
src/typescript/typescript.txt

Minor edits to the “Learn TypeScript” course

---

src/rxjs/0-basics.md
src/rxjs/2-clean-card-number.txt
src/rxjs/4-debugging.txt
src/rxjs/rxjs.md

Minor edits to the “Learn RxJS” course

---

src/javascript/5-context.md
src/javascript/6-prototypes.md
src/javascript/7-classes.md
src/javascript/8-promises.md
src/javascript/javascript.md

Minor edits to the “Advanced JavaScript” course

---

src/dom/1-functional-utilities.md
src/dom/2-finding-elements.md
src/dom/4-attributes-and-properties.md
src/dom/5-layout.md
src/dom/dom.md

Minor edits to the “DOM and jQuery” course

---

src/canjs/2-define-todo/define-todo.md

Minor edits to the “Learn CanJS” course

---

src/angular/11-declarative-state/declarative-state.md
src/angular/12-writing-unit-tests/writing-unit-tests.md
src/angular/13-nested-routes/nested-routes.md
src/angular/14-building-order-form/building-order-form.md
src/angular/15-directive/15-directive.md
src/angular/16-order-service/order-service.md
src/angular/17-order-history-component/order-history-component.md
src/angular/18-item-total-pipe/item-total-pipe.md
src/angular/3-creating-components/creating-components.md
src/angular/3a-pipes/3a-pipes.md
src/angular/4-adding-routing/adding-routing.md
src/angular/5-creating-navigation/creating-navigation.md
src/angular/6-restaurant-service/restaurant-service.md
src/angular/7-pull-restaurant-data-into-view/pull-restaurant-data-into-view.md
src/angular/8-state-city-options/state-city-options.md
src/angular/9-form-value-changes/form-value-changes.md
src/angular/angular.md

Minor edits to the “Learn Angular” course

---

src/advanced-typescript/02-generics-with-constraints/generics-with-constraints.md
src/advanced-typescript/03-index-accessed-types/index-accessed-types.md
src/advanced-typescript/04-mapped-types/mapped-types.md
src/advanced-typescript/05-conditional-types/conditional-types.md
src/advanced-typescript/06-template-literal-types/template-literal-types.md
src/advanced-typescript/advanced-typescript.md
src/advanced-typescript/scripts/README.md

Minor edits to the “Advanced TypeScript” course

---

src/react-native/01-intro-to-react-native/intro-to-react-native.md
src/react-native/02-setting-up-your-environment/setting-up-your-environment.md
src/react-native/03-creating-a-new-app/creating-a-new-app.md
src/react-native/15-using-asyncstorage/using-asyncstorage.md

This also replaces the old React content with blank outlines so we can make sure that the course only has correct information.

Update React Native pages with blank outlines

---

src/react-vite/01-intro-to-react/intro-to-react.md
src/react-vite/02-setting-up-your-environment/setting-up-your-environment.md
src/react-vite/03-intro-to-jsx/intro-to-jsx.md
src/react-vite/04-components/components.md
src/react-vite/07-styling-in-react/styling-in-react.md
src/react-vite/12-testing/testing.md
src/react-vite/react.md

Minor edits to the “Learn React” course

---

src/react-native/05-intro-to-testing/intro-to-testing.md

- Add placeholder problems and solutions for Section 05 of React Native training
- Updates Skeleton for the .md file.
It's likely taht the skeleton may become smaller or longer depending on the approach for this section, with no pre-existing problems or solutions, it was hard to measure without comparing this to the existing React training.
Also, by this part of the training, the only thing we could teach is testing elements that appear on the screen since there is no  user input in the application at this point, which may be fine, just something worth noting.

(LD-258) Introduction to Testing breakdown

---

exercises/typescript/07-functions/01-problem/package.json
exercises/typescript/07-functions/01-solution/package.json
exercises/typescript/09-interfaces/01-problem/package.json
exercises/typescript/09-interfaces/01-solution/package.json
exercises/typescript/09-interfaces/02-problem/package.json
exercises/typescript/09-interfaces/02-solution/package.json
exercises/typescript/11-generics/01-problem/package.json
exercises/typescript/11-generics/01-solution/package.json
exercises/typescript/11-generics/02-problem/package.json
exercises/typescript/11-generics/02-solution/package.json
exercises/typescript/12-utility-types/01-problem/package.json
exercises/typescript/12-utility-types/01-solution/package.json
exercises/typescript/12-utility-types/02-problem/package.json
exercises/typescript/12-utility-types/02-solution/package.json
exercises/typescript/12-utility-types/03-problem/package.json
exercises/typescript/12-utility-types/03-solution/package.json
exercises/typescript/12-utility-types/04-problem/package.json
exercises/typescript/12-utility-types/04-solution/package.json
exercises/typescript/12-utility-types/05-problem/package.json
exercises/typescript/12-utility-types/05-solution/package.json

This fixes the path in the `test` script to find the test files.

Fix the TypeScript exercise test commands

---

src/react-native/05-intro-to-testing/intro-to-testing.md

Adds content for Introduction to Testing section of React Native training

(LD-298) Write content for 'Introduction to Testing'

---

src/react-vite/02-setting-up-your-environment/setting-up-your-environment.md

Image paths should always be relative in Bitovi Academy.

Fix an image path in the React DOM course

---

src/react-native/react-native.md

This adds content to the very first page in the React Native course.
It’s mostly a copy of what we have for React. Later, I’d like to go back and expand it a bit more.

Add content to the main React Native page

---

src/react-native/03-creating-a-new-app/creating-a-new-app.md

- Use the correct command for specifying a version when creating a new app.
- Specify the major versions of other dependencies.
- Other minor fixes.

Minor edits to the “Creating a New Application” page

---

exercise-src/react-native/04-intro-to-jsx/01-problem/App.tsx
exercise-src/react-native/04-intro-to-jsx/02-problem/App.tsx
src/react-native/04-intro-to-jsx/intro-to-jsx.md

- Improve the exercises by giving more code in the Setup.
- Fix the file paths for the exercise files.
- Add TODO placeholders for explaining the core components.

Refine the “Introduction to JSX” page

---

exercise-src/react-native/11-navigation/03-solution/src/components/RestaurantHeader/RestaurantHeader.test.tsx
exercise-src/react-native/11-navigation/03-solution/src/components/RestaurantHeader/RestaurantHeader.tsx
exercise-src/react-native/11-navigation/03-solution/src/components/RestaurantHeader/index.ts
exercise-src/react-native/11-navigation/03-solution/src/components/RestaurantHeader/mocks.ts
exercise-src/react-native/11-navigation/03-solution/src/screens/RestaurantDetails/RestaurantDetails.test.tsx
exercise-src/react-native/11-navigation/03-solution/src/screens/RestaurantDetails/RestaurantDetails.tsx
exercise-src/react-native/11-navigation/03-solution/src/screens/RestaurantList/RestaurantList.test.tsx
exercise-src/react-native/11-navigation/03-solution/src/screens/RestaurantList/RestaurantList.tsx

The tests had all of the finished code in the app and needed to be pared down to what was needed just for this exercise.

Fix the exercise 3 solution tests for Navigation

---

exercise-src/react-native/12-navigation-params/01-solution/src/screens/CityList/CityList.test.tsx
exercise-src/react-native/12-navigation-params/01-solution/src/screens/CityList/CityList.tsx
exercise-src/react-native/13-http-requests/01-solution/src/App.test.tsx
exercise-src/react-native/13-http-requests/01-solution/src/components/Loading/Loading.test.tsx
exercise-src/react-native/13-http-requests/01-solution/src/components/Loading/Loading.tsx
exercise-src/react-native/13-http-requests/01-solution/src/components/Loading/index.ts
exercise-src/react-native/13-http-requests/01-solution/src/screens/CityList/CityList.test.tsx
exercise-src/react-native/13-http-requests/01-solution/src/screens/CityList/CityList.tsx
exercise-src/react-native/13-http-requests/01-solution/src/screens/RestaurantDetails/RestaurantDetails.test.tsx
exercise-src/react-native/13-http-requests/01-solution/src/screens/RestaurantList/RestaurantList.test.tsx
exercise-src/react-native/13-http-requests/01-solution/src/screens/StateList/StateList.test.tsx
exercise-src/react-native/13-http-requests/01-solution/src/services/pmo/api/api.test.ts
package.json

All the tests pass, but infortunately the `App` tests have a warning: https://bitovi.slack.com/archives/C06MAPYJF8B/p1715204909099589?thread_ts=1715204901.431429&cid=C06MAPYJF8B

Fix the exercise solution tests for “Making HTTP Requests”

---

exercise-src/react-native/09-react-context/01-problem/src/App.tsx
exercise-src/react-native/11-navigation/01-problem/src/App.tsx
exercise-src/react-native/11-navigation/01-solution/src/App.tsx
exercise-src/react-native/11-navigation/02-problem/src/App.tsx
exercise-src/react-native/11-navigation/02-solution/src/App.tsx
exercise-src/react-native/11-navigation/03-problem/src/App.tsx
exercise-src/react-native/11-navigation/03-solution/src/App.tsx
exercise-src/react-native/12-navigation-params/01-problem/src/App.tsx
exercise-src/react-native/12-navigation-params/02-problem/src/App.tsx
exercise-src/react-native/14-user-input/01-problem/src/App.tsx
exercise-src/react-native/14-user-input/01-problem/src/screens/RestaurantOrder/RestaurantOrder.tsx
exercise-src/react-native/14-user-input/01-solution/src/App.tsx
exercise-src/react-native/14-user-input/01-solution/src/components/FormSwitch/FormSwitch.tsx
exercise-src/react-native/14-user-input/01-solution/src/screens/RestaurantOrder/RestaurantOrder.tsx
exercise-src/react-native/14-user-input/02-problem/src/components/FormTextField/FormTextField.tsx
exercise-src/react-native/14-user-input/02-problem/src/screens/RestaurantOrder/RestaurantOrder.tsx
exercise-src/react-native/14-user-input/02-solution/src/components/FormTextField/FormTextField.tsx
exercise-src/react-native/14-user-input/02-solution/src/screens/RestaurantOrder/RestaurantOrder.tsx
exercise-src/react-native/15-async-storage/02-solution/src/App.tsx
exercise-src/react-native/16-security/01-solution/src/App.tsx
exercise-src/react-native/17-offline/01-solution/src/App.tsx
exercise-src/react-native/17-offline/01-solution/src/screens/RestaurantDetails/RestaurantDetails.tsx

Most of the changes in this are addressing comments that were made in this review: https://github.com/bitovi/academy/pull/728#pullrequestreview-2053761962

Fix minor issues in the exercise code for React Native

---

exercise-src/react-native/11-navigation/01-problem/src/App.tsx
exercise-src/react-native/14-user-input/02-problem/src/components/FormTextField/FormTextField.tsx
exercise-src/react-native/15-async-storage/01-solution/src/services/pmo/api/api.ts
exercise-src/react-native/15-async-storage/02-problem/src/services/DataMigration/DataMigration.test.tsx
exercise-src/react-native/15-async-storage/02-problem/src/services/pmo/api/api.ts
src/react-native/04-intro-to-jsx/intro-to-jsx.md
src/react-native/07-debugging-devtools/debugging-devtools.md
src/react-native/09-react-context/react-context.md
src/react-native/11-navigation/navigation.md
src/react-native/12-navigation-params/navigation-params.md
src/react-native/14-user-inputs/set-state-with-function.tsx
src/react-native/14-user-inputs/switch.tsx
src/react-native/14-user-inputs/text-accessible-useId.tsx
src/react-native/14-user-inputs/text-accessible.tsx
src/react-native/14-user-inputs/text.tsx
src/react-native/14-user-inputs/typescript-record-interface.tsx
src/react-native/14-user-inputs/user-inputs.md

It is heavily based on the React DOM content: https://www.bitovi.com/academy/learn-react/controlled-vs-uncontrolled.html
This also includes other very minor text changes.
Closes https://bitovi.atlassian.net/browse/LD-307

Write the content for “Handling User Inputs”

---

exercise-src/react-native/03-creating-a-new-app/01-solution/android/app/build.gradle
exercise-src/react-native/03-creating-a-new-app/01-solution/android/app/src/main/java/com/solution/MainActivity.kt
exercise-src/react-native/03-creating-a-new-app/01-solution/android/app/src/main/java/com/solution/MainApplication.kt
exercise-src/react-native/03-creating-a-new-app/01-solution/android/app/src/main/res/values/strings.xml
exercise-src/react-native/03-creating-a-new-app/01-solution/android/settings.gradle
exercise-src/react-native/03-creating-a-new-app/01-solution/ios/Podfile
exercise-src/react-native/03-creating-a-new-app/01-solution/ios/solution.xcodeproj/project.pbxproj
exercise-src/react-native/03-creating-a-new-app/01-solution/ios/solution.xcodeproj/xcshareddata/xcschemes/solution.xcscheme
exercise-src/react-native/03-creating-a-new-app/01-solution/ios/solution.xcworkspace/contents.xcworkspacedata
exercise-src/react-native/03-creating-a-new-app/01-solution/ios/solution/AppDelegate.mm
exercise-src/react-native/03-creating-a-new-app/01-solution/ios/solution/Info.plist
exercise-src/react-native/03-creating-a-new-app/01-solution/ios/solution/LaunchScreen.storyboard
exercise-src/react-native/11-navigation/01-problem/android/app/build.gradle

Should hopefully cover all needed PlaceMyOrder references

Change 'solution' references back to 'PlaceMyOrder'

---

exercises/react-vite/03-intro-to-jsx/01-solution/src/App.tsx
exercises/react-vite/03-intro-to-jsx/02-problem/src/App.tsx
src/react-vite/03-intro-to-jsx/intro-to-jsx.md
src/react-vite/06-routing/routing.md

Changes were made while doing find and replace fixes in React Native.

Minor changes to the React (Vite) code

---

src/react-native/15-using-asyncstorage/clear.ts
src/react-native/15-using-asyncstorage/getAllKeys.ts
src/react-native/15-using-asyncstorage/getItem.ts
src/react-native/15-using-asyncstorage/setItem.ts
src/react-native/15-using-asyncstorage/using-asyncstorage.md

This is a rough draft of all the content for Objective 1. The second objective (and the rest of the page) will be fleshed out in another commit.

Add the Objective 1 content for “Using AsyncStorage”

---

README.md

This documents the `lint` and `test` commands we have in the root `package.json`.

Add some instructions to the readme about linting & testing

---

src/react-native/02-setting-up-your-environment/setting-up-your-environment.md

Add a note about disabling Core Isolation to the Intel HAXM instructions.

Update “Setting Up Your Environment”

---

exercise-src/react-native/03-creating-a-new-app/01-solution/android/app/build.gradle
exercise-src/react-native/03-creating-a-new-app/01-solution/android/app/src/main/java/com/solution/MainActivity.kt
exercise-src/react-native/03-creating-a-new-app/01-solution/android/app/src/main/java/com/solution/MainApplication.kt
exercise-src/react-native/11-navigation/01-problem/android/app/build.gradle

This replaces `com.PlaceMyOrder` with `com.placemyorder` everywhere. I confirmed that new apps are generated with an all-lowercase package name.

Fix com.placemyorder

---

exercise-src/react-native/17-offline-support/01-problem/src/screens/Settings/Settings.tsx
exercise-src/react-native/17-offline-support/02-problem/src/services/pmo/favorite/hooks.ts
exercise-src/react-native/17-offline-support/02-solution/src/screens/RestaurantDetails/RestaurantDetails.tsx
exercise-src/react-native/17-offline-support/02-solution/src/services/pmo/favorite/hooks.ts
exercise-src/react-native/17-offline-support/03-problem/src/services/pmo/favorite/hooks.ts
exercise-src/react-native/17-offline-support/03-solution/src/services/pmo/favorite/hooks.ts
src/react-native/17-offline-support/isConnected.tsx
src/react-native/17-offline-support/offline-support.md

The exercise code needs to be refactored, so the content does the best it can with the code as-is.
The content takes a departure from our normal approach by explaining the code that will be given in the Setup steps because there is a lot to explain about syncing, so it seems like using our code as an example will be the most useful way to explain the concepts.
Closes https://bitovi.atlassian.net/browse/LD-310

Write the content for “Adding Offline Support”

---

exercise-src/react-native/19-performance/01-problem/src/screens/RestaurantList/RestaurantList.tsx
exercise-src/react-native/19-performance/01-solution/src/screens/RestaurantList/RestaurantList.tsx
src/react-native/19-performance-optimization/import-dynamic-suspense.tsx
src/react-native/19-performance-optimization/import-dynamic.tsx
src/react-native/19-performance-optimization/import-static.tsx
src/react-native/19-performance-optimization/performance-optimization.md

Closes https://bitovi.atlassian.net/browse/LD-312

Write the content for “Performance and Optimization”

---

src/react-native/17-offline-support/offline-support.md

This adds:
- The page description.
- Content under Overview.
This also fixes a couple minor issues.

Fix a couple TODOs on “Adding Offline Support”

---

exercise-src/react-native/.eslintrc.js
exercise-src/react-native/03-creating-a-new-app/03-solution/.eslintrc.js
src/react-native/.eslintrc.js

Seems like it should not have been set to `off`.

Remove the “off” setting for jest/prefer-hooks-in-order

---

src/react-native/03-creating-a-new-app/creating-a-new-app.md
src/react-native/04-intro-to-jsx/intro-to-jsx.md
src/react-native/07-debugging-devtools/debugging-devtools.md

Refine the “Creating a New Application” page and others

---

src/react-native/04-intro-to-jsx/intro-to-jsx.md

- Improve the Overview.
- Use `const` for components instead of `function`.
- Add highlighting for more of the code examples.

Minor edits to “Introduction to JSX”

---

exercise-src/react-native/03-creating-a-new-app/03-solution/tsconfig.json
src/react-native/03-creating-a-new-app/creating-a-new-app.md

This also adds the `@diff` to the “Creating a New Application” page.

Update the tsconfig.json to include *.tsx files

---

exercise-src/react-native/16-security/01-problem/src/screens/Settings/Settings.tsx
exercise-src/react-native/16-security/01-problem/src/services/auth/AuthProvider.test.tsx
exercise-src/react-native/16-security/01-problem/src/services/auth/AuthProvider.tsx
exercise-src/react-native/16-security/01-solution/src/services/auth/AuthProvider.tsx
src/react-native/16-security-and-auth/configuring.ts
src/react-native/16-security-and-auth/security-and-auth.md
src/react-native/16-security-and-auth/signIn.ts

- Add more hints to the exercises.
- Give more in the exercises so they’re a little easier.

Refine the “Security and Authentication” page

---

exercise-src/react-native/18-maps/01-problem/.gitignore
src/react-native/18-maps/maps.md

Also, add a couple files that were missing from the exercise instructions.

Add `secrets.properties` to the `.gitignore`

---

src/react-native/20-building/building.md
src/react-native/21-publishing-and-updating/publishing-and-updating.md

Expand the content to focus on the concepts and point learners to the React Native docs for the “how.”

Refine the Building, Publishing, & Updating content

---

src/technology-consulting/1-effort.md
src/technology-consulting/2-specific-goals.md
src/technology-consulting/3-prioritization.md
src/technology-consulting/4-development.md
src/technology-consulting/5-communication.md
src/technology-consulting/6-building-rapport.md
src/technology-consulting/7-setting-expectations.md
src/technology-consulting/8-sales-to-delivery.md
src/technology-consulting/9-ending-a-project.md
src/technology-consulting/consultant-vs-technologist.md

This:
- Adds a brand new “Being a Consultant” page that includes all new content.
- Adds new sections to the “Building Trust and Rapport” and “Setting Expectations” pages.
- Includes other minor edits to existing content.
Part of https://bitovi.atlassian.net/browse/LD-10

Add a rough draft of the Consulting training content

---

src/technology-consulting/consultant-vs-technologist.md

This includes many edits to improve the content.

Refine the “Being a Consultant” page

---

src/technology-consulting/6-building-rapport.md

This includes many edits to improve the content.

Refine the “Building Trust and Rapport” page

---

src/technology-consulting/7-setting-expectations.md

This includes many edits to improve the content.

Refine the “Setting Expectations” page

---

src/technology-consulting/6-building-rapport.md
src/technology-consulting/7-setting-expectations.md
src/technology-consulting/consultant-vs-technologist.md

Edits while making the slides.

Refine the Consulting training

---

src/technology-consulting/7-setting-expectations.md
src/technology-consulting/consultant-vs-technologist.md

These are edits before finishing the dry run with Principals.

Finish first-draft edits to the Consulting training

---

src/technology-consulting/6-building-rapport.md
src/technology-consulting/7-setting-expectations.md
src/technology-consulting/consultant-vs-technologist.md

This rearranges the sections and rewrites some of the content to match how it’ll be delivered during the training.
Part of https://bitovi.atlassian.net/browse/LD-381

Refine the Consulting training for the first cohort

---

static/styles/styles.less

Makes the On This Page section of the content scrollable

Make 'On This Page...' section Scrollable

---

src/program-management-with-jira/13-manage.md
src/technology-consulting/5-communication.md
src/technology-consulting/6-building-rapport.md
src/technology-consulting/7-setting-expectations.md
src/technology-consulting/consultant-vs-technologist.md

This rearranges the sections and rewrites some of the content to match how it’s delivered during the training.

Refine the Consulting training content

---

src/technology-consulting/7-setting-expectations.md
src/technology-consulting/consultant-vs-technologist.md

This improves the content to more thoroughly match what’s included in the presentation.

Refine the day 2 Consulting training content

---

src/technology-consulting/5-communication.md

Part of https://bitovi.atlassian.net/browse/LD-612

Refine the Communication training content

---

src/technology-consulting/10-consultant-vs-technologist.md
src/technology-consulting/11-understanding-business.md
src/technology-consulting/12-setting-expectations.md
src/technology-consulting/13-continuously-learning.md
src/technology-consulting/14-sales-to-delivery.md
src/technology-consulting/15-ending-a-project.md
src/technology-consulting/5-communication.md
src/technology-consulting/6-communication-styles.md
src/technology-consulting/7-communication-methods.md
src/technology-consulting/8-giving-receiving-feedback.md
src/technology-consulting/9-building-rapport.md

This makes it a little bit easier to navigate the content.

Split up the Communication training pages

---

src/technology-consulting/5-communication.md

Renamed it to “Planning communication” and refined the content.
Closes https://bitovi.atlassian.net/browse/LD-724

Refine the “Fundamental principles” section

---

src/technology-consulting/5-communication.md

- Refine the “Emotional intelligence” section
- Rename the “Building strong social communication skills” section to “Nonverbal communication”
- Refine the “Business writing” section
- Rename the “Effectively using tools to improve communication” section to “Communication tools”
Closes https://bitovi.atlassian.net/browse/LD-725
Closes https://bitovi.atlassian.net/browse/LD-727
Closes https://bitovi.atlassian.net/browse/LD-728
Closes https://bitovi.atlassian.net/browse/LD-729

Refine a few of the Communication sections

---

src/technology-consulting/6-communication-methods.md

Closes https://bitovi.atlassian.net/browse/LD-731

Refine the “Effectively communicating in meetings” section

---

src/technology-consulting/6-communication-methods.md

Closes https://bitovi.atlassian.net/browse/LD-733

Refine the “Choosing the best method of communication” section

---

src/technology-consulting/6-communication-styles.md

Closes https://bitovi.atlassian.net/browse/LD-734

Refine the “Communication styles: Understanding ourselves” section

---

src/technology-consulting/6-communication-styles.md

Closes https://bitovi.atlassian.net/browse/LD-735

Refine the “Communication styles: Understanding others” section

---

src/technology-consulting/6-communication-styles.md

Closes https://bitovi.atlassian.net/browse/LD-736

Refine the “Communication styles: Adapting to others” section

---

src/technology-consulting/5-communication.md
src/technology-consulting/8-giving-receiving-feedback.md

Closes https://bitovi.atlassian.net/browse/LD-737

Refine the “Giving and receiving feedback” section

---

src/technology-consulting/11-understanding-business.md
src/technology-consulting/5-communication.md
src/technology-consulting/6-communication-methods.md

Part of https://bitovi.atlassian.net/browse/LD-686

Refine content for the Communication training

---

src/technology-consulting/5-communication.md
src/technology-consulting/6-communication-styles.md

Part of https://bitovi.atlassian.net/browse/LD-691

Refine content for the third group’s first day

---

src/technology-consulting/8-giving-receiving-feedback.md

Part of https://bitovi.atlassian.net/browse/LD-693

Clean up the “Giving and Receiving Feedback” page

---

src/bit-u.md

Also, add `alt` attributes to all the images on this page.
Closes https://bitovi.atlassian.net/browse/LD-827

Add React Native to Bitovi Academy landing page

---

.github/workflows/verify-build-publish.yml

https://bitovi.atlassian.net/browse/FE-249
- [] Short description of changes:
This PR will allow us to run the failing deploy action on the fix Hub Spot branch
https://github.com/bitovi/academy/pull/913

allowing deploying on fix hubspot branch

---

.github/workflows/verify-build-publish.yml

https://bitovi.atlassian.net/browse/FE-249
This PR will allow us to run the failing deploy action on the fix Hub Spot branch

Allow deploy on certain branch

---

src/react-native/10-managing-state/managing-state.md

https://bitovi.atlassian.net/browse/FE-255
removing an underscore in the academy lesson

removed underscore in text

---

exercise-src/react-native/03-creating-a-new-app/01-solution/babel.config.js
exercise-src/react-native/03-creating-a-new-app/01-solution/package-lock.json
exercise-src/react-native/03-creating-a-new-app/01-solution/package.json
exercise-src/react-native/03-creating-a-new-app/02-solution/package-lock.json
exercise-src/react-native/03-creating-a-new-app/02-solution/package.json
exercise-src/react-native/03-creating-a-new-app/03-solution/babel.config.js
exercise-src/react-native/03-creating-a-new-app/03-solution/package-lock.json
exercise-src/react-native/03-creating-a-new-app/03-solution/package.json
exercise-src/react-native/07-debugging/01-solution/package-lock.json
exercise-src/react-native/07-debugging/01-solution/package.json
exercise-src/react-native/07-debugging/02-solution/package.json
exercise-src/react-native/11-navigation/01-problem/package-lock.json
exercise-src/react-native/11-navigation/01-problem/package.json
exercise-src/react-native/11-navigation/02-problem/package-lock.json
exercise-src/react-native/11-navigation/02-problem/package.json
exercise-src/react-native/13-http-requests/01-problem/babel.config.js
exercise-src/react-native/13-http-requests/01-problem/package-lock.json
exercise-src/react-native/13-http-requests/01-problem/package.json
exercise-src/react-native/15-async-storage/01-problem/package-lock.json
exercise-src/react-native/15-async-storage/01-problem/package.json
exercise-src/react-native/16-security/01-problem/package-lock.json
exercise-src/react-native/16-security/01-problem/package.json
exercise-src/react-native/17-offline-support/01-problem/package-lock.json
exercise-src/react-native/17-offline-support/01-problem/package.json
exercise-src/react-native/18-maps/01-problem/package-lock.json
exercise-src/react-native/18-maps/01-problem/package.json
exercise-src/react-native/20-building/01-solution/package.json

https://bitovi.atlassian.net/browse/FE-252
Adding a new package and updating the babel config

package and config update for alias

---

src/react-native/05-intro-to-testing/intro-to-testing.md
src/react-native/11-navigation/navigation.md
src/react-native/14-user-inputs/user-inputs.md
src/react-native/16-security-and-auth/security-and-auth.md
src/react-native/18-maps/maps.md
src/react-native/19-performance-optimization/performance-optimization.md

https://bitovi.atlassian.net/browse/FE-250
Links in the academy were navigating users to 404 pages

FE-250 fixing broken links

---

src/technology-consulting/5-communication.md
src/technology-consulting/8-giving-receiving-feedback.md

Some improvements from January based on earlier trainings.

Update “Effective Communication” page
