- static/styles/styles.less
- Reduce left margin on navigation list as width decreases
- If width decreases more than nav width the contact button gets hidden
> Adjust header to accomodate collapse

- static/styles/styles.less
Tested Chrome, FF, and Safari.
Was:
Is now:
> Removed html height 100% as not needed by safari

- src/angular/angular.md
- src/bit-u.md
- src/debugging-javascript/debugging-javascript.md
- src/dom/dom.md
- src/javascript/javascript.md
- src/rxjs/rxjs.md
- src/typescript/typescript.md
- src/web-components/web-components.md
- templates/content.mustache
We should always link to https://www.bitovi.com/community/slack in case the invite link changes.
> Fix the Slack invite links

- src/typescript/typescript.md
Remove the heading tag from image to prevent blank link being created on the `bit-toc` component.
> remove heading from image

- package.json
- static/styles/prism.less
- static/styles/styles.less
> Upgrade bit-docs-html-codepen-link and code buttons styles

- src/react/2-intro-to-jsx.md
- src/react/5-styling-in-react.md
- src/react/9-managing-complex-state.md
> 218 react minor edits

- src/react/1-setting-up-your-environment.md
- src/react/2-intro-to-jsx.md
- src/react/react.md
#218 Made a couple of small edits that made the intro lessons easier to understand.
> 218 React updates for Dec 28th training

- src/angular/2-building-first-app/app.component.spec.ts
- src/angular/2-building-first-app/building-first-app.md
- update angular 11 references to 13
- remove angular2-inline plugin because it is not relevant anymore (VSCode provides same features by default)
- update npm install command to angular 13
- use HTML comments in .html files
- link to official documentation in extra options of `ng new` command
- update workspace file tree
- replace "global app level" with "module level"
- update tsconfig.json and index.html files
- correctly reference Angular 12 as version that started strict mode as default
> Page Updates: building-our-first-app

- src/rxjs/0-basics.md
- src/rxjs/1-angular.md
- src/rxjs/10-show-paying.md
- src/rxjs/11-disable-while-pending.md
- src/rxjs/2-clean-card-number.md
- src/rxjs/8-disable-pay-button.md
- src/rxjs/9-request-payment.md
Update links to the RxJS documentation site to point to the current `rxjs.dev` domain instead of the firebase or reactivex domains.
> Page Updates: update rxjs documentation site links

- src/angular/16-order-service/2-order.service.spec.ts
- src/angular/16-order-service/order-service.md
Address issues described in NGACAD-54 (https://bitovi.atlassian.net/browse/NGACAD-54?atlOrigin=eyJpIjoiMjk1ZjBhZWE3Y2YzNGRjNjg1YzJiYjIyMjZkZmMyZGQiLCJwIjoiaiJ9)
P2 Setup:
P2 What You Need To Know:
> Angular: fix order-service issues

- src/angular/9-form-value-changes/form-value-changes.md
Combine two instructions for clarity
> Angular: remove redundant instruction

- static/static.js
- static/styles/styles.less
- templates/content.mustache
- templates/layout.mustache
https://bitovi.atlassian.net/browse/SALES-28
This is how I've implemented it, please let me know if you'd like changes:
If user is on an internal page (any page nested after the top level), such as the ones between "Learn React" and "View More Courses"
After 30 seconds of being on the page, on scroll of the content, if they've passed 20% of the content height (roughly middle of the 2nd header's block on most pages), prompt for their email:
The field, label, email validation, and button are all coming from this embedded hubspot form:
https://app.hubspot.com/forms/2171535/822ba57d-1707-4eb0-9b1b-ef5815f33506/performance
the rest of the modal is built into the repo code in this PR
As soon as the form is successfully submitted, the popover close, hubspot sends an email to this address:
and …
> Prompt Student for their email to continue, use cookie to not prompt again once done

- src/angular/11-declarative-state/mergeMap.html
- src/angular/11-declarative-state/pairwise.html
- src/angular/11-declarative-state/shareReplay.html
https://bitovi.atlassian.net/browse/NGACAD-80
Renamed all car terms to menu item terms. Each new menu item term is found directly in the `place-my-order` shop:
Here is the mapping I did:
beetle -> Steamed Mussels (21.99)
mustang (40000) -> Truffle Noodles (14.99)
camaro (38000) -> Charred Octopus (25.99)
corvette -> Gunthorp Chicken (21.99)
tesla model s -> Onion fries (15.99)
> feat(angular) - renamed all car terms to menu item terms

- src/angular/14-building-order-form/child-component/order-2.component.html
- src/angular/14-building-order-form/child-component/order-starter.component.html
- src/angular/14-building-order-form/child-component/order.component-childcomponent.html
- src/angular/14-building-order-form/child-component/order.component-props.html
- src/angular/14-building-order-form/order.component-final.html
- src/angular/14-building-order-form/order.component-starter.html
- src/angular/14-building-order-form/order.component-withtabs.html
- src/angular/15-directive/15-directive.md
- src/angular/15-directive/order.component.directive.html
- src/angular/16-order-service/order.component.html
- src/angular/18-item-total-pipe/order.component.html
https://bitovi.atlassian.net/browse/NGACAD-79
Removed "form-control" class from templates since they appear to not be needed for styles:
>It should be safe to remove this classname since all elements affected are `input` elements with type `text`. Based on the screenshot above, the styles from `form-control` are all overridden by `input[type=text]`
Removing the use of this classname since it can be confusing to developers new to `FormControl` in Angular. The classname doesn't do anything in terms of styling or for Angular's forms.
> feat(angular) - removed form-control class since it is not needed

- src/ngrx/3-ngrx-init/ngrx-init.md
The added npm install part is a bit redundant since it's already listed as a step in the previous section (oops). I've reworded it so it makes more sense why we're suggesting it again
> feat(ngrx) - npm install revision

- src/ngrx/12-test-reducer/login.reducer.spec.ts
Testing Reducers Section uses the wrong file for its reducer spec at https://www.bitovi.com/academy/learn-ngrx/test-reducer.html
Currently it has the tests for the selectors when it should have the tests for the reducer: https://github.com/bitovi/angular-ngrx-chat/compare/create-reducer...test-reducer#diff-f82d08b6735d964986e66f959793dc506e941c42672dbe73b940e1bfd56b4142R1
> fix(ngrx): replaced reducer spec with correct file

- static/styles/styles.less
- templates/layout.mustache
Currently, anchor tags are updated programmatically to open new tabs. To avoid this behavior, I've updated the close "button" to use a button tag instead of an anchor tag. I've added some styles to remove the button appearance so aesthetically nothing has changed.
> SALES-118 changed tag from anchor to button

- README.md
- src/bit-u.md
Community calendar is now actively maintained again, so it's being added back with minor copy changes changes.
> Reinstate community calendar

- scripts/hubspot-deploy/academy-page.js
- scripts/hubspot-deploy/hubspot-api.js
- scripts/hubspot-deploy/hubspot-publisher.js
Hubspot’s v2 api was not returning all pages when we requested them.  We were not hitting the limit. It appears to be a bug that they fixed in v3 of their API.  The bug was causing some pages to be re-created even though they already existed.  Hubspot was appending an integer for a while then began appending a timestamp to avoid overwriting the existing page.  Looking at the timestamps of the published pages, this has been a problem since December 2020, and 80 copies of each erroring page have been mistakenly published.
I tested the code on the `learn-docker` pages and it successfully updated the files.  Before publishing the entire site, I’m going to let somebody else take a look and run the code.
There was some previous work done to say how many pages need to be deleted.  I updated the …
> Fix deploy with Hubspot API v3

- exercises/angular/6-restaurant-service/problem/src/app/restaurant/restaurant.component.spec.ts
- src/angular/10-updating-service-params/restaurant.component-httpparams.ts
- src/angular/10-updating-service-params/restaurant.service-httpparams.spec.ts
- src/angular/10-updating-service-params/updating-service-params.md
- src/angular/12-writing-unit-tests/order-state/restaurant.service.spec.ts
- src/angular/12-writing-unit-tests/restaurant.service.spec-withrestaurant.ts
- src/angular/12-writing-unit-tests/restaurant.service.spec.ts
- src/angular/12-writing-unit-tests/writing-unit-tests.md
- src/angular/16-order-service/2-order.service.spec.ts
- src/angular/6-restaurant-service/restaurant.service-with-interface.spec.ts
- src/angular/9-form-value-changes/restaurant.service-citystate.spec.ts
- src/angular/9-form-value-changes/restaurant.service-generics.spec.ts
Lots of minor fixes to the text and code, including renaming this page.
> Clean up the “Multi-parameter Services” section

- src/react-vite/01-intro-to-react/intro-to-react.md
- src/react-vite/02-setting-up-your-environment/setting-up-your-environment.md
- src/react-vite/03-intro-to-jsx/intro-to-jsx.md
- src/react-vite/04-components/components.md
- src/react-vite/05-routing/routing.md
- src/react-vite/06-props/props.md
- src/react-vite/07-styling-in-react/styling-in-react.md
- src/react-vite/08-stateful-hooks/stateful-hooks.md
- src/react-vite/09-side-effects/side-effects.md
- src/react-vite/10-controlled-vs-uncontrolled/controlled-vs-uncontrolled.md
- src/react-vite/11-data-fetching/data-fetching.md
- src/react-vite/12-testing/testing.md
After explaining the Overview/Objective/Concepts/Requirements/Setup/Verify/Solution structure to @rlmcneary2 and @rjspencer, we realized that it would make more sense for the “requirements” to be closer to the solution so folks know exactly what they’re trying to accomplish and have a reference while they’re coding a solution.
As part of this, we’re renaming Requirements to Exercise so it also aligns with how we structured the slides.
> Move the Requirements to be before the Solution

- exercises/react-vite/.gitignore
- exercises/react-vite/09-making-http-requests/01-solution/.env
- exercises/react-vite/09-making-http-requests/01-solution/.env.development
This makes it so `.env` files can be included in the React exercises.
> Don’t ignore .env in the React exercises

- README.md
- src/react-vite/12-testing/testing.md
I made minor attempts to make this more "portable." The example code used to illustrate the objective is embedded in the page, rather than referring to "real" code from PMO. I did not change the exercise code - waiting to see if people think that's necessary.
While simpler exercise code with less PMO code around it seems like a good idea, it might also be a "jarring" change from previous the context of previous examples that always built on PMO.
> Update React Testing Object 1.

- exercises/angular/6-restaurant-service/problem/src/app/app.component.spec.ts
- src/angular/10-updating-service-params/restaurant.component-httpparams.spec.ts
- src/angular/11-declarative-state/restaurant.component.spec.ts
- src/angular/13-nested-routes/app.component.spec.ts
- src/angular/14-building-order-form/app.component.spec.ts
- src/angular/17-order-history-component/app.component.spec.ts
- src/angular/18-item-total-pipe/app.component.spec.ts
- src/angular/5-creating-navigation/app.component.spec.ts
- src/angular/7-pull-restaurant-data-into-view/app.component.spec.ts
- src/angular/8-state-city-options/app.component.spec.ts
- src/angular/9-form-value-changes/restaurant.component-citystate.spec.ts
- make tests more forgiving by allowing different template formatting
- allow a different solution to `should make the home navigation link class active when the router navigates to "/" path` test that requires additional detectChanges
- update test description to be a list of restaurants instead of the wrong list of cities
> angular training improvements

- exercises/typescript/04-exporting-and-importing/01-problem/package-lock.json
- exercises/typescript/04-exporting-and-importing/01-problem/package.json
- exercises/typescript/04-exporting-and-importing/01-problem/src/exporting-and-importing/exporter.ts
- exercises/typescript/04-exporting-and-importing/01-problem/src/exporting-and-importing/importer.test.ts
- exercises/typescript/04-exporting-and-importing/01-problem/src/exporting-and-importing/importer.ts
- exercises/typescript/04-exporting-and-importing/01-problem/src/hello-world/hello-world.ts
- exercises/typescript/04-exporting-and-importing/01-problem/tsconfig.json
- exercises/typescript/04-exporting-and-importing/01-solution/package-lock.json
- exercises/typescript/04-exporting-and-importing/01-solution/package.json
- exercises/typescript/04-exporting-and-importing/01-solution/src/exporting-and-importing/exporter.ts
- exercises/typescript/04-exporting-and-importing/01-solution/src/exporting-and-importing/importer.test.ts
- exercises/typescript/04-exporting-and-importing/01-solution/src/exporting-and-importing/importer.ts
- exercises/typescript/04-exporting-and-importing/01-solution/src/hello-world/hello-world.ts
- exercises/typescript/04-exporting-and-importing/01-solution/tsconfig.json
- src/typescript/04-configuration/configuration.md
- src/typescript/05-exporting-and-importing/exporting-and-importing.md
This creates a separate page for the “Exporting and Importing” exercise that was part of the “Configuration” page. They seemed to have nothing to do with each other, so I think this makes more sense.
Note how the tests are done for the exercise. We instruct learners to add use this for the `test` script in their `package.json`:
```
node --require ts-node/register --test src/**/**.test.**
```
This will look for any `.test.` file and run it with [Node’s test runner](https://nodejs.org/api/test.html). We do not need Mocha or any other dependency.
> Move “Exporting and Importing” out of “Configuration”

- src/technology-consulting/5-communication.md
Previously, a lot of the main content on the “Effective Communication” page was hidden behind `<details>` elements, so it was more difficult to read the page, search, etc.
This removes those elements from the main content but leaves them for the exercises.
> Move content out of `details` elements

- src/typescript/01-why-typescript/why-typescript.md
- Rearranged the content on the page to separate what TypeScript is vs. why it’s worth using.
- Expanded the content in each section.
- Removed the “Using this guide” section (it’s now on the Learn TypeScript page).
> Improve the “Why TypeScript” page

- src/react-native/01-intro-to-react-native/intro-to-react-native.md
This implements the general suggestions in this comment:
https://github.com/bitovi/academy/pull/679#discussion_r1588650668
In summary: this focuses the content on React Native and what differentiates it and removes the general explanations of React.
This is definitely a starting draft that can be improved in the future.
> Update the “Introduction to React Native” page

- src/react-native/05-intro-to-testing/EmailInputField.test.1.tsx
- src/react-native/05-intro-to-testing/EmailInputField.test.2.tsx
- src/react-native/05-intro-to-testing/EmailInputField.tsx
- src/react-native/05-intro-to-testing/intro-to-testing.md
- Move the code examples to files so they’re easier to work with.
- Replace mentions of frontend and browser development (because the learners aren’t expected to know frontend dev).
> Minor updates to the “Introduction to Testing” page

- src/typescript/01-why-typescript/buggy-assignment.js
- src/typescript/01-why-typescript/buggy-assignment.ts
- src/typescript/01-why-typescript/buggy-call.js
- src/typescript/01-why-typescript/buggy-call.ts
- src/typescript/01-why-typescript/enums.ts
- src/typescript/01-why-typescript/why-typescript.md
- Move the code examples to separate files so `@diff` can be used with them.
- Keep each section focused on one main code example.
- Add the full TypeScript errors with error numbers.
> Minor refinements to the “Why TypeScript” page

- exercise-src/generate.mjs
- exercise-src/react-native/03-creating-a-new-app/01-solution/package-lock.json
- exercise-src/react-native/03-creating-a-new-app/02-solution/package-lock.json
- exercise-src/react-native/03-creating-a-new-app/03-solution/package-lock.json
- exercise-src/react-native/06-custom-components/01-solution/App.tsx
- exercise-src/react-native/06-custom-components/02-problem/App.tsx
- exercise-src/react-native/06-custom-components/02-solution/App.tsx
- exercise-src/react-native/06-custom-components/03-problem/src/App.tsx
- exercise-src/react-native/06-custom-components/03-solution/src/App.tsx
- exercise-src/react-native/06-custom-components/03-solution/src/screens/StateList/StateList.tsx
- exercise-src/react-native/07-debugging/01-solution/package-lock.json
- exercise-src/react-native/07-debugging/02-solution/package-lock.json
- exercise-src/react-native/07-debugging/02-solution/src/screens/StateList/StateList.tsx
- exercise-src/react-native/08-styling/01-problem/src/screens/StateList/components/ListItem/ListItem.test.tsx
- exercise-src/react-native/08-styling/01-solution/src/screens/StateList/components/ListItem/ListItem.tsx
- exercise-src/react-native/09-react-context/01-problem/src/screens/StateList/components/ListItem/ListItem.tsx
- exercise-src/react-native/11-navigation/01-solution/jest.config.js
- exercise-src/react-native/11-navigation/01-solution/package-lock.json
- exercise-src/react-native/11-navigation/01-solution/package.json
- exercise-src/react-native/11-navigation/01-solution/src/App.test.tsx
- exercise-src/react-native/11-navigation/01-solution/src/screens/Settings/Settings.test.tsx
- exercise-src/react-native/11-navigation/01-solution/src/screens/StateList/StateList.test.tsx
- exercise-src/react-native/11-navigation/01-solution/src/screens/StateList/StateList.tsx
- exercise-src/react-native/11-navigation/02-solution/jest-setup.ts
- exercise-src/react-native/11-navigation/02-solution/package-lock.json
- exercise-src/react-native/11-navigation/02-solution/package.json
- exercise-src/react-native/11-navigation/02-solution/src/screens/CityList/CityList.test.tsx
- exercise-src/react-native/11-navigation/02-solution/src/screens/StateList/StateList.test.tsx
- exercises/tests.mjs
- package.json
This adds a `test` script that will run the tests in every exercise solution folder. This should help us always have working exercise solutions and avoid regressions.
This work is not 100% complete, but I’d like to merge it in as-is because it’s definitely an improvement over what we have.
Here’s what still needs to be done:
- Fix all the exercise solutions; right now, they should be correct through `exercises/react-native/11-navigation/02-solution`.
- Replace the `generate` script run in the CI run with the `test` script (this can be done after all the tests pass).
Some notes on changes to the exercises:
- A `package-lock.json` was added to the first solution because 1) that reflects the actual solution and 2) that makes it possible to use `npm ci` for all the solution folders.
- I …
> Add a test script

- src/react-native/06-building-custom-components/building-custom-components.md
- src/react-native/06-building-custom-components/button-function.tsx
- src/react-native/06-building-custom-components/reused-button-in-app.tsx
- src/react-native/06-building-custom-components/sample-index.ts
- src/react-native/06-building-custom-components/submit-button-and-props-destructured.tsx
- src/react-native/06-building-custom-components/submit-button-and-props.tsx
- src/react-native/06-building-custom-components/submit-button-use.tsx
- Removed `.module.css` because we don’t have CSS files in React Native.
- Add `<Text>` components inside `<Pressable>` because that’s how it’s actually used.
- Replaced the `alert()` call because it doesn’t exist in React Native.
> Refine the “Building Custom Components” content

- src/react-native/13-making-http-requests/dependency-array-undefined.tsx
Added `<Text>` components inside `<Pressable>` because that’s how it’s actually used.
> Fix the Pressable example in Making HTTP Requests

- exercise-src/react-native/11-navigation/02-problem/src/screens/StateList/StateList.tsx
- exercise-src/react-native/11-navigation/02-solution/src/App.tsx
- exercise-src/react-native/11-navigation/02-solution/src/screens/StateList/StateList.tsx
- exercise-src/react-native/11-navigation/03-problem/src/App.tsx
- exercise-src/react-native/11-navigation/03-problem/src/screens/RestaurantDetails/RestaurantDetails.tsx
- exercise-src/react-native/11-navigation/03-problem/src/screens/RestaurantList/RestaurantList.tsx
- exercise-src/react-native/11-navigation/03-solution/src/App.tsx
- exercise-src/react-native/11-navigation/03-solution/src/screens/RestaurantDetails/RestaurantDetails.tsx
- exercise-src/react-native/11-navigation/03-solution/src/screens/RestaurantList/RestaurantList.tsx
This updates the exercises for the “Navigation” module by removing 1) the parameters that were passed in `navigation.navigate()` calls and 2) the route props that were passed into components.
All of the navigation parameter-related code will be covered in “Storing State in Navigation Parameters,”
> Remove the navigation params from “Navigation”

- src/react-native/02-setting-up-your-environment/setting-up-your-environment.md
- Add a new section for stuff that didn’t belong in the Overview.
- Remove the erroneous `ANDROID_SDK_ROOT` notes.
- Improve a lot of the Windows instructions.
> Refine the “Setting Up Your Environment” page

- .github/workflows/verify-build-publish.yml
This will help us catch errors before they’re merged in.
> Run the tests for every PR

- exercises/tests.mjs
I sometimes run into issues with the test script where it is unable to delete the `node_modules` folder after running an exercise solution’s test.
Since this step is not critical to whether the tests have passed or not, these errors will now be caught and logged, but ignored so the script can keep running.
I’d like to look into why I’m seeing these failures, but in the meantime, I think this improves the script for anyone else who might run into a similar issue.
> Make the exercise test command more resilient to failures

- exercise-src/react-native/13-http-requests/03-problem/src/services/pmo/api/api.ts
- exercise-src/react-native/13-http-requests/03-solution/src/services/pmo/api/api.ts
The `keyPrefix` isn’t needed until Async Storage, so this removes it from the earlier exercise code.
> Fix keyPrefix being added to early

- README.md
- exercises/tests.mjs
- package.json
This improves the time it takes to run the exercise solution tests by running them in parallel.
Below are the results of multiple test runs in GitHub and on a MacBook Pro. It looks like about three tests running in parallel is optimal in both environments, so the `test` script will max out at running three tests at a time.
First run in GitHub CI:
```
┌─────────┬───────┬───────────────┬─────────────┐
│ (index) │ limit │ time          │ formatted   │
├─────────┼───────┼───────────────┼─────────────┤
│ 0       │ 4     │ 787608.631378 │ '13:07.608' │
│ 1       │ 3     │ 461751.497619 │ '7:41.751'  │
│ 2       │ 2     │ 475695.005603 │ '7:55.695'  │
│ 3       │ 1     │ 646006.242796 │ '10:46.006' │
└─────────┴───────┴───────────────┴─────────────┘
```
Second run (after changing the max limit …
> Run the tests in parallel

- src/typescript/05-modules/modules.md
For example was accidentally changed to header, rather than bold:
> fix: convert heading to bold, remove empty file, remove unnecessary snippet

- exercise-src/react-native/03-creating-a-new-app/02-solution/App.tsx
- exercise-src/react-native/03-creating-a-new-app/03-solution/App.tsx
- exercise-src/react-native/04-intro-to-jsx/01-problem/App.tsx
- exercise-src/react-native/04-intro-to-jsx/01-solution/App.tsx
- exercise-src/react-native/04-intro-to-jsx/02-problem/App.tsx
- src/react-native/04-intro-to-jsx/SafeAreaView.tsx
- src/react-native/04-intro-to-jsx/ScrollView.tsx
- src/react-native/04-intro-to-jsx/View.tsx
- src/react-native/04-intro-to-jsx/intro-to-jsx.md
This rearranges some of the exercise code across the “Create a New App” and “Intro to JSX” pages:
- “Create a New App” now only uses `<Text>`
- “Intro to JSX” (objective 1) introduces the `View`, `ScrollView`, and `SafeArea` components.
- The first exercise has learners use those components.
This fixes the issue that Objective 1’s exercise had learners use interpolation, which hadn’t been taught yet.
> Improve the content & exercises for “Introduction to JSX”

- exercise-src/react-native/.prettierrc.js
- exercise-src/react-native/03-creating-a-new-app/03-solution/.prettierrc.js
- src/react-native/.prettierrc.js
This adds `endOfLine: "auto"` to the Prettier config so CRLF line endings are respected on Windows.
> Fix CRLF issues with Prettier

- src/react-native/05-intro-to-testing/EmailInputField.test.1.tsx
- src/react-native/05-intro-to-testing/EmailInputField.test.2.tsx
- src/react-native/05-intro-to-testing/EmailInputField.test.3.tsx
- src/react-native/05-intro-to-testing/EmailInputField.tsx
- src/react-native/05-intro-to-testing/EmailInputField.xml
- src/react-native/05-intro-to-testing/intro-to-testing.md
- src/react-native/09-react-context/react-context.md
- src/react-native/11-navigation/navigation.md
- src/react-native/12-navigation-params/navigation-params.md
- src/react-native/15-using-asyncstorage/using-asyncstorage.md
- Add the rendered `EmailInputField` JSX to the content.
- Make the example code match our guidelines.
- Replace old DOM/element references with components/views.
- Replace mentions with `user-event` as a separate package with `userEvent` as the API provided by RNTL.
> Improve the “Introduction to Testing” page

- src/react-native/19-performance-optimization/performance-optimization.md
This points out that the `npm start` logs will show the new bundle after completing the exercise.
> Add Verify instructions to “Performance and Optimization”

- static/static.js
- static/styles/styles.less
window.history.state was null thus the eventListener on scroll couldn't finish running, added push state after checking hash so that it should always have a value on load
> Fix Bug in Academy: Not remembering scroll position.

- package.json
- static/static.js
- static/styles/styles.less
This fixes a bug where if you click something in the TOC and reload, then scroll somewhere else, you will be scrolled back to the anchor you clicked
This completely refactors how the header, sidebar, main content, and table of contents (TOC) are laid out.
Previously, JS was required to keep track of the scroll position on reload. This caused bugs (like the wrong position being restored on reload if you clicked a link in the TOC) and led to some features being lost (like the “tap to scroll to the top of the page” in Safari).
Now, the browser is able to keep track of the scroll position for the page, so no JS is required and the CSS layout is more robust.
> Fix scrolling bug in Academy

- static/styles/styles.less
Previously, the TOC would display underneath the sidebar all the way until when all three columns were able to be next to each other.
Now, between the one-column and three-column layouts, there’s a new two-column layout that will show the TOC next to the sidebar.
> Make the TOC display next to the sidebar at smaller widths

- src/technology-consulting/5-communication.md
- src/technology-consulting/6-communication-methods.md
Part of https://bitovi.atlassian.net/browse/LD-691
> Refine content for the third Communication group’s second day

- src/react-native/react-native.md
https://bitovi.atlassian.net/browse/FE-248
The link on the intro page that navigates to the first lesson was broken. It was missing a `-native` in the URL.
> fixed link on the first page
